data_dir: /Users/yicheng/kaggle/kaggle-child-mind-institute-detect-sleep-states/data
processed_dir: /Users/yicheng/kaggle/kaggle-child-mind-institute-detect-sleep-states/processed_data
output_dir: /Users/yicheng/kaggle/kaggle-child-mind-institute-detect-sleep-states/output
model_dir: /Users/yicheng/kaggle/kaggle-child-mind-institute-detect-sleep-states/output/train
sub_dir: ./